### PR TITLE
removed unused time dependency

### PR DESCRIPTION
**Pull request by FND**
unless I overlooked something, this isn't actually being used anymore - removal should eliminate the installation issue mentioned in #119

### CODE REVIEW

**Comment by mikedeboer** [comment]
Very true. Thanks!

**Comment by FND** [comment]
On a related note (not sure this warrants a separate issue): Do you intend to release a new version any time soon? v0.3.2 is now almost two years old, and it seems awkward to depend on a moving target like the master branch.

**Comment by mikedeboer** [comment]
You're right :) I'll try to publish 0.4 asap.

**Comment by FND** [comment]
Excellent, thank you!

**Pull request merged**
